// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkDeviceScanner;

namespace NetworkDeviceScanner.Migrations
{
    [DbContext(typeof(NetworkDeviceScannerContext))]
    partial class NetworkDeviceScannerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("NetworkDeviceScanner.Models.DiscoveredDevice", b =>
                {
                    b.Property<string>("MacAddress")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12);

                    b.Property<string>("CustomName")
                        .HasMaxLength(255);

                    b.Property<DateTimeOffset>("LastSeen");

                    b.HasKey("MacAddress");

                    b.ToTable("DiscoveredDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
