// <auto-generated />
using System;
using Kamiizumi.NetworkDeviceScanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kamiizumi.NetworkDeviceScanner.Data.Migrations
{
    [DbContext(typeof(NetworkDeviceScannerContext))]
    [Migration("20190310181512_AddUserDefinedNameToDevice")]
    partial class AddUserDefinedNameToDevice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1");

            modelBuilder.Entity("Kamiizumi.NetworkDeviceScanner.Data.Models.Device", b =>
                {
                    b.Property<string>("MacAddress")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(17);

                    b.Property<DateTimeOffset?>("LastSeen")
                        .IsRequired();

                    b.Property<string>("UserDefinedName")
                        .HasMaxLength(255);

                    b.HasKey("MacAddress");

                    b.ToTable("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
