// <auto-generated />
using System;
using Kamiizumi.NetworkDeviceScanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kamiizumi.NetworkDeviceScanner.Data.Migrations
{
    [DbContext(typeof(NetworkDeviceScannerContext))]
    partial class NetworkDeviceScannerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1");

            modelBuilder.Entity("Kamiizumi.NetworkDeviceScanner.Data.Models.Device", b =>
                {
                    b.Property<string>("MacAddress")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(17);

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .IsRequired();

                    b.Property<string>("LastSeenHostName")
                        .HasMaxLength(63);

                    b.Property<string>("LastSeenIp")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int?>("ProfileId");

                    b.Property<string>("UserDefinedName")
                        .HasMaxLength(255);

                    b.HasKey("MacAddress");

                    b.HasIndex("ProfileId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Kamiizumi.NetworkDeviceScanner.Data.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Kamiizumi.NetworkDeviceScanner.Data.Models.Device", b =>
                {
                    b.HasOne("Kamiizumi.NetworkDeviceScanner.Data.Models.Profile", "Profile")
                        .WithMany("Devices")
                        .HasForeignKey("ProfileId");
                });
#pragma warning restore 612, 618
        }
    }
}
